# Generated by Django 5.0.3 on 2025-04-19 16:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=20, unique=True, verbose_name='رقم العقد')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الإيجار الشهري (ر.ع.)')),
                ('payment_terms', models.CharField(choices=[('MONTHLY', 'شهري'), ('QUARTERLY', 'ربع سنوي'), ('SEMI_ANNUAL', 'نصف سنوي'), ('ANNUAL', 'سنوي')], default='MONTHLY', max_length=20, verbose_name='فترة الدفع')),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الضمان المالي (ر.ع.)')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('PENDING', 'بانتظار التوقيع'), ('ACTIVE', 'نشط'), ('EXPIRED', 'منتهي'), ('TERMINATED', 'ملغى')], default='DRAFT', max_length=20, verbose_name='حالة العقد')),
                ('terms_and_conditions', models.TextField(verbose_name='الشروط والأحكام')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوقيع')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('signed_by_landlord', models.ForeignKey(limit_choices_to={'user_type__in': ['INVESTOR', 'OWNER']}, on_delete=django.db.models.deletion.PROTECT, related_name='signed_landlord_contracts', to=settings.AUTH_USER_MODEL, verbose_name='موقع من المالك')),
                ('signed_by_tenant', models.ForeignKey(limit_choices_to={'user_type': 'TENANT'}, on_delete=django.db.models.deletion.PROTECT, related_name='signed_tenant_contracts', to=settings.AUTH_USER_MODEL, verbose_name='موقع من المستأجر')),
                ('tenant', models.ForeignKey(limit_choices_to={'user_type': 'TENANT'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='المستأجر')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'عقد إيجار',
                'verbose_name_plural': 'عقود الإيجار',
                'ordering': ['-start_date'],
                'permissions': [('can_sign_contract', 'يمكنه توقيع العقود')],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='contracts_documents/', verbose_name='الملف')),
                ('description', models.CharField(max_length=200, verbose_name='وصف الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'ملف العقد',
                'verbose_name_plural': 'ملفات العقود',
            },
        ),
        migrations.CreateModel(
            name='ContractTermination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_date', models.DateField(verbose_name='تاريخ الإنهاء')),
                ('reason', models.CharField(max_length=200, verbose_name='سبب الإنهاء')),
                ('penalty_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ الغرامة (ر.ع.)')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ الاسترداد (ر.ع.)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_terminations', to=settings.AUTH_USER_MODEL, verbose_name='تمت الموافقة بواسطة')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminations', to='contracts.contract', verbose_name='العقد')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_terminations', to=settings.AUTH_USER_MODEL, verbose_name='تم البدء بواسطة')),
            ],
            options={
                'verbose_name': 'إنهاء العقد',
                'verbose_name_plural': 'إنهاءات العقود',
                'ordering': ['-termination_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment_number', models.CharField(max_length=20, unique=True, verbose_name='رقم التعديل')),
                ('reason', models.CharField(max_length=200, verbose_name='سبب التعديل')),
                ('changes', models.TextField(verbose_name='التغييرات المطبقة')),
                ('new_monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الإيجار الشهري الجديد (ر.ع.)')),
                ('new_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء الجديد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False, verbose_name='تمت الموافقة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_amendments', to=settings.AUTH_USER_MODEL, verbose_name='تمت الموافقة بواسطة')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='contracts.contract', verbose_name='العقد الاصلي')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'تعديل العقد',
                'verbose_name_plural': 'تعديلات العقود',
                'ordering': ['-created_at'],
                'unique_together': {('contract', 'amendment_number')},
            },
        ),
    ]
