# Generated by Django 5.0.2 on 2025-04-17 22:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('OWNER', 'مالك المبني'), ('INVESTOR', 'مستثمر شركة مالكة'), ('TENANT', 'مستأجر شركة'), ('SIGNER', 'مفوض التوقيع'), ('ADMIN', 'مسؤول النظام')], max_length=10, verbose_name='نوع المستخدم')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='اسم الشركة')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('is_authorized', models.BooleanField(default=False, verbose_name='مفعل')),
                ('commercial_registration', models.CharField(blank=True, max_length=50, verbose_name='السجل التجاري')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('groups', models.ManyToManyField(blank=True, help_text='المجموعات التي ينتمي إليها هذا المستخدم', related_name='customuser_groups', related_query_name='customuser', to='auth.group', verbose_name='المجموعات')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='الصلاحيات المحددة لهذا المستخدم', related_name='customuser_permissions', related_query_name='customuser', to='auth.permission', verbose_name='صلاحيات المستخدم')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
