# Generated by Django 5.0.3 on 2025-04-19 16:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نوع الوحدة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'نوع الوحدة',
                'verbose_name_plural': 'أنواع الوحدات',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المبني')),
                ('location', models.CharField(max_length=255, verbose_name='الموقع')),
                ('city', models.CharField(max_length=50, verbose_name='المدينة')),
                ('total_floors', models.PositiveIntegerField(verbose_name='عدد الطوابق')),
                ('description', models.TextField(blank=True, verbose_name='وصف المبني')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'INVESTOR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
            ],
            options={
                'verbose_name': 'مبني',
                'verbose_name_plural': 'المباني',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20, verbose_name='رقم الوحدة')),
                ('floor', models.PositiveIntegerField(verbose_name='الطابق')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المساحة')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الإيجار الشهري (ر.ع.)')),
                ('status', models.CharField(choices=[('VACANT', 'شاغرة'), ('OCCUPIED', 'مشغولة'), ('UNDER_MAINTENANCE', 'قيد الصيانة')], default='VACANT', max_length=20, verbose_name='الحالة')),
                ('features', models.TextField(blank=True, verbose_name='المميزات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.building', verbose_name='المبني')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.unittype', verbose_name='نوع الوحدة')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'الوحدات',
                'ordering': ['building', 'floor', 'unit_number'],
                'unique_together': {('building', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='UnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='unit_images/', verbose_name='صورة')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='وصف الصورة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'صورة الوحدة',
                'verbose_name_plural': 'صور الوحدات',
            },
        ),
    ]
